-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\CornerDetectionHDL\Convert_Levels.vhd
-- Created: 2023-06-21 14:30:32
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Convert_Levels
-- Source Path: CornerDetectionHDL/HDL Corner Algorithm/Convert Levels
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Convert_Levels IS
  PORT( HarrisIn                          :   IN    std_logic_vector(43 DOWNTO 0);  -- sfix44
        PixelOut                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END Convert_Levels;


ARCHITECTURE rtl OF Convert_Levels IS

  -- Signals
  SIGNAL HarrisIn_signed                  : signed(43 DOWNTO 0);  -- sfix44
  SIGNAL Data_Type_Conversion_out1        : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  HarrisIn_signed <= signed(HarrisIn);

  
  Data_Type_Conversion_out1 <= "11111111" WHEN (HarrisIn_signed(43) = '0') AND (HarrisIn_signed(42 DOWNTO 8) /= "00000000000000000000000000000000000") ELSE
      "00000000" WHEN HarrisIn_signed(43) = '1' ELSE
      unsigned(HarrisIn_signed(7 DOWNTO 0));

  PixelOut <= std_logic_vector(Data_Type_Conversion_out1);

END rtl;

