-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\CornerDetectionHDL\Color_Space_Converter.vhd
-- Created: 2023-06-21 14:30:32
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Color_Space_Converter
-- Source Path: CornerDetectionHDL/HDL Corner Algorithm/RGB2Bin/Color Space Converter
-- Hierarchy Level: 2
-- 
-- Color Space Converter
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HDL_Corner_Algorithm_pkg.ALL;

ENTITY Color_Space_Converter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        in0                               :   IN    vector_of_std_logic_vector8(0 TO 2);  -- uint8 [3]
        in1_hStart                        :   IN    std_logic;
        in1_hEnd                          :   IN    std_logic;
        in1_vStart                        :   IN    std_logic;
        in1_vEnd                          :   IN    std_logic;
        in1_valid                         :   IN    std_logic;
        out0                              :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        out1_hStart                       :   OUT   std_logic;
        out1_hEnd                         :   OUT   std_logic;
        out1_vStart                       :   OUT   std_logic;
        out1_vEnd                         :   OUT   std_logic;
        out1_valid                        :   OUT   std_logic
        );
END Color_Space_Converter;


ARCHITECTURE rtl OF Color_Space_Converter IS

  -- Component Declarations
  COMPONENT RGB2INTENSITY
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          R                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          G                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          B                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          hStartIn                        :   IN    std_logic;
          hEndIn                          :   IN    std_logic;
          vStartIn                        :   IN    std_logic;
          vEndIn                          :   IN    std_logic;
          validIn                         :   IN    std_logic;
          Intensity                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          hStartOut                       :   OUT   std_logic;
          hEndOut                         :   OUT   std_logic;
          vStartOut                       :   OUT   std_logic;
          vEndOut                         :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : RGB2INTENSITY
    USE ENTITY work.RGB2INTENSITY(rtl);

  -- Signals
  SIGNAL in0_unsigned                     : vector_of_unsigned8(0 TO 2);  -- uint8 [3]
  SIGNAL pixelInReg                       : vector_of_unsigned8(0 TO 2);  -- uint8 [3]
  SIGNAL hStartInReg                      : std_logic;
  SIGNAL hEndInReg                        : std_logic;
  SIGNAL vStartInReg                      : std_logic;
  SIGNAL vEndInReg                        : std_logic;
  SIGNAL validInReg                       : std_logic;
  SIGNAL pixelOut                         : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL hStartOut                        : std_logic;
  SIGNAL hEndOut                          : std_logic;
  SIGNAL vStartOut                        : std_logic;
  SIGNAL vEndOut                          : std_logic;
  SIGNAL validOut                         : std_logic;

BEGIN
  u_rgb2intensityNet_inst : RGB2INTENSITY
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              R => std_logic_vector(pixelInReg(0)),  -- uint8
              G => std_logic_vector(pixelInReg(1)),  -- uint8
              B => std_logic_vector(pixelInReg(2)),  -- uint8
              hStartIn => hStartInReg,
              hEndIn => hEndInReg,
              vStartIn => vStartInReg,
              vEndIn => vEndInReg,
              validIn => validInReg,
              Intensity => pixelOut,  -- uint8
              hStartOut => hStartOut,
              hEndOut => hEndOut,
              vStartOut => vStartOut,
              vEndOut => vEndOut,
              validOut => validOut
              );

  outputgen: FOR k IN 0 TO 2 GENERATE
    in0_unsigned(k) <= unsigned(in0(k));
  END GENERATE;

  reg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        pixelInReg <= (OTHERS => to_unsigned(16#00#, 8));
      ELSIF enb = '1' THEN
        pixelInReg <= in0_unsigned;
      END IF;
    END IF;
  END PROCESS reg_process;


  reg_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        hStartInReg <= '0';
      ELSIF enb = '1' THEN
        hStartInReg <= in1_hStart;
      END IF;
    END IF;
  END PROCESS reg_1_process;


  reg_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        hEndInReg <= '0';
      ELSIF enb = '1' THEN
        hEndInReg <= in1_hEnd;
      END IF;
    END IF;
  END PROCESS reg_2_process;


  reg_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        vStartInReg <= '0';
      ELSIF enb = '1' THEN
        vStartInReg <= in1_vStart;
      END IF;
    END IF;
  END PROCESS reg_3_process;


  reg_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        vEndInReg <= '0';
      ELSIF enb = '1' THEN
        vEndInReg <= in1_vEnd;
      END IF;
    END IF;
  END PROCESS reg_4_process;


  reg_5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        validInReg <= '0';
      ELSIF enb = '1' THEN
        validInReg <= in1_valid;
      END IF;
    END IF;
  END PROCESS reg_5_process;


  out1_hStart <= hStartOut;

  out1_hEnd <= hEndOut;

  out1_vStart <= vStartOut;

  out1_vEnd <= vEndOut;

  out1_valid <= validOut;

  out0 <= pixelOut;

END rtl;

